### ISSUE TITLE
add Not Found Page to Docs

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/autobot#103]
When a route/URL that doesn't exist is hit, we would like the user to be routed to a 404 page which alerts them that the page they're trying to access doesn't exist.

To create this page, create a new file docs/404.md that will act as the Not Found page.

**Comment by moses-kisakye** [comment]
### Checkout
[GH-3b66295](https://github.com/OSCA-Kampala-Chapter/autobot/pull/109/commits/3b662959984cbc6f50c184d83f53974b9487b4ff)

**Comment by moses-kisakye** [comment]
I think this issues needs to be closed
