### ISSUE TITLE
Link Documentation Navigation Items to respective pages

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/autobot#104]
The Documentation Navigation menu has broken links. The menu items should link to respective pages; for instance `Home` should link to home page, `FAQS` should link to FAQS page, name it all....

![Image](https://user-images.githubusercontent.com/65954740/202792883-016bba91-d3cc-460f-886a-8a0d9e8da12f.png)

**Comment by moses-kisakye** [comment]
can i get my self assigned to this?

**Comment by HassanBahati** [comment]
> can i get my self assigned to this?

Yah sure, feel free to take it on

**Comment by HassanBahati** [comment]
issue was resolved, thanks @mosespace
