### ISSUE TITLE
ci deploy is still failing

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#125]
@HassanBahati there is still some failure with the docs deployment. Are you guys looking into it?

**Comment by kallyas** [comment]
This is caused by missing plugin

```
ERROR    -  Config value 'plugins': The "mkdocstrings" plugin is not installed
```

**Comment by HassanBahati** [comment]
> @HassanBahati there is still some failure with the docs deployment. Are you guys looking into it?

lets inspect
