### ISSUE TITLE
Add properties to the telegram objects

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#13]
So far we have empty telegram classes to represent telegram objects. We need to add properties to these objects. Properties  are those attributes of the telegram objects as shown on the telegram bot api page [here](https://core.telegram.org/bots/api). The format we're gonna use to add properties is by declaring them in the classes `__init__` function. For example.

```python
class User:
    def __init__(self,
        id = None,
        is_bot = None,
        first_name = None,
        last_name = None,
        username = None,
        language_code = None,
        is_premium = None,
        added_to_attached_menu = None,
        can_join_groups = None,
        can_read_all_group_messages = None,
        supports_inline_queries = None
    ):

        self.id = id
        self.is_bot = is_bot
        self.first_name = first_name
        self.last_name = last_name
        self.username = username
        self.language_code = language_code
        self.is_premium = is_premium
        self.added_to_attached_menu = added_to_attached_menu
        self.can_join_groups = can_join_groups
        self.can_read_all_group_messages = can_read_all_group_messages 
        self.supports_inline_queries = supports_inline_queries
```

**Comment by edger-asiimwe** [comment]
@ht-thomas shouldn't the properties with **Optional** be initialized with type **None**

**Comment by ht-thomas** [comment]
@edger-asiimwe that is what we're doing by using None as the default value in the arguments we're passing to `__init__`

**Comment by ht-thomas** [comment]
@edger-asiimwe we need a way to track down the objects that have been worked on for this so that we do not clash working on the same objects. We'll track whatever has been worked on with the list below

- [x] User
- [x] Chat
- [x] Message
- [x] MessageId
- [x] MessageEntity
- [x] PhotoSize
- [x] Animation
- [x] Audio
- [x] Document
- [x] Video
- [x] VideoNote
- [x] Voice
- [x] Contact
- [x] Dice
- [x] PollOption
- [x] PollAnswer
- [x] Poll
- [x] Location
- [x] Venue
- [x] WebAppData
- [x] ProximityAlertTriggered
- [x] MessageAutoDeleteTimerChanged
- [x] VideoChatScheduled
- [x] VideoChatStarted
- [x] VideoChatEnded
- [x] VideoChatParticipantsInvited
- [x] UserProfilePhotos
- [x] File
- [x] WebAppInfo
- [x] ReplyKeyboardMarkup
- [x] KeyboardButton
- [x] KeyboardButtonPollType
- [x] ReplyKeyboardRemove
- [x] InlineKeyboardMarkup
- [x] InlineKeyboardButton
- [x] LoginUrl
- [x] CallbackQuery
- [x] ForceReply
- [x] ChatPhoto
- [x] ChatInviteLink
- [x] ChatAdministratorRights
- [x] ChatMember
- [x] ChatMemberOwner
- [x] ChatMemberAdministrator
- [x] ChatMemberMember
- [x] ChatMemberRestricted
- [x] ChatMemberLeft
- [x] ChatMemberBanned
- [x] ChatMemberUpdated
- [x] ChatJoinRequest
- [x] ChatPermissions
- [x] ChatLocation
- [x] BotCommand
- [x] BotCommandScope
- [x] BotCommandScopeDefault
- [x] BotCommandScopeAllPrivateChats
- [x] BotCommandScopeAllGroupChats
- [x] BotCommandScopeAllChatAdministrattos
- [x] BotCommandScopeChat
- [x] BotCommandScopeChat
- [x] BotCommandScopeChatAdministrators
- [x] BotCommandScopeChatMember
- [x] MenuButton
- [x] MenuButtonCommands
- [x] MenuButtonWebApp
- [x] MenuButtonDefault
- [x] ResponsePrarameters
- [x] InputMedia
- [x] InputMediaPhoto
- [x] InputMediaVideo
- [x] InputMediaAnimation
- [x] InputMediaAudio
- [x] InputMediaDocument
- [x] InputFile

**Comment by edger-asiimwe** [comment]
@ht-thomas I am unable to check the task list items

**Comment by ht-thomas** [comment]
@edger-asiimwe I get I'll be updating it after merging relevant PRs

**Comment by ht-thomas** [comment]
I decided to work on a different way to populate the object classes, this issue is not so relevant anymore
