### ISSUE TITLE
[Docs] Edit link on the docs references master branch

### ISSUE THREAD

**Issue by kallyas** [OSCA-Kampala-Chapter/autobot#140]
I have noticed that the edit link on the documentation references master branch of which we don't have a branch named master

Eg: [Edit this page](https://github.com/OSCA-Kampala-Chapter/autobot/edit/master/docs/objects.md)

@HassanBahati do you have any solution

**Comment by mosespace** [comment]
@kallyas I think i should remove it

> it's of no use

**Comment by kallyas** [comment]
@HassanBahati

**Comment by HassanBahati** [comment]
@kallyas thank you for identifying this, the solution should be to fix the broken link so that we point towards main rather than master

**Comment by HassanBahati** [comment]
About getting rid of it...i don't agree to that. I feel this is a convention in docs of open source source.

Most if not all open source documentations that have `Edit on GitHub` feature for various sections.

Refer to 
[GitHub Documentation](https://docs.github.com/en) 
[NodeJs Documentation](https://nodejs.org/en/docs/)
among others

**Comment by HassanBahati** [comment]
The only challenge i see is that the just the pencil icon doesn't seem elaborative enough to give a call to action, though this may not be high priority at the moment

**Comment by mosespace** [comment]
> The only challenge i see is that the just the pencil icon doesn't seem elaborative enough to give a call to action, though this may not be high priority at the moment

of course we can consider that later!! :+1:

**Comment by kallyas** [comment]
I think this has been fixed, thus closing this Issue
