### ISSUE TITLE
replace parameters in api methods with keyword arguments

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#148]
The different parameters in all classes in api modules should be removed and replaced with **kwargs. This will help us remove the overhead of constructing a dictionary needed to make api requests. The docstrings and return value can remain the same

**Comment by ht-thomas** [comment]
@ushergodwin can you handle this?

**Comment by ushergodwin** [comment]
Sure, I can. 
How do you intend to handle required parameters during method implementation? 

Check the existence of required parameters in kwargs, then throw an exception if any are missing?

How about having positional required argument, ( can also be *args) and then the optional ones can go in (kwargs). 

Am looking for away that would involve a lot of processing while validating the calls. 

Let me know what you think.

**Comment by ht-thomas** [comment]
@ushergodwin we shall delegate the task of checking for required arguments off to telegram. We shall pass on the error raised by telegram to the handler

**Comment by ushergodwin** [comment]
@ht-thomas Ohh, okay, that's more convenient. Thanks for the clarification.
