### ISSUE TITLE
make all api methods async

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#149]
since we're going to primarily make async network calls, all the api methods interacting with the network have to be async.
This is just as simple as adding `async` in front of `def` on all the api methods

**Comment by ht-thomas** [comment]
@ushergodwin is it possible to work on this while you work on the other issue

**Comment by ushergodwin** [comment]
Yes, I will make 2 commits referencing these 2 issues..
