### ISSUE TITLE
Add properties to the telegram objects [REVISED]

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#24]
I've reworked a way of populating properties into the specific object classes. Instead of using the old way in gh-13, we shall use `__slots__` instead, and only place non-optional parameters in the `__init__` function signature. so for the example as in the previous issue using the users object, it'd be written like this:

```python
class User:
    __slots__ = (
        "id",
        "is_bot",
        "first_name",
        "last_name",
        "username",
        "language_code",
        "is_premium",
        "added_to_attached_menu",
        "can_join_groups",
        "can_read_all_group_messages",
        "supports_inline_queries",
    )

    def __init__ (self,id,is_bot,first_name):
        self.id = id
        self.is_bot = is_bot
        self.first_name = first_name
        self.last_name = None
        self.username = None
        self.language_code = None
        self.is_premium = None
        self.added_to_attached_menu = None
        self.can_join_groups = None
        self.can_read_all_group_messages = None
        self.supports_inline_queries = None
```
### Documentation
It would be best to also add documentation for the object we fill in so that it's easier for us to not go back and document code in the future. This is an example from @ushergodwin 
```python
class InputMediaPhoto(BaseObject):
    """Represents a photo to be sent.

        Args:
            type (str): Type of the result, must be photo

            media (str): File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name.

            caption (str): Optional. Caption of the photo to be sent, 0-1024 characters after entities parsing

            parse_mode 	(str): Optional. Mode for parsing entities in the photo caption

            caption_entities (list): Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
    """

    __slots__ = (
        "caption",
        "parse_mode",
        "caption_entities"
    )

    def __init__(self, type, media):
        self.type = type
        self.media = media
        self.caption = None 
        self.parse_mode = None
        self.caption_entities = None
```
### Pending objects
- [x] User
- [x] Update
- [x] Message
- [x] MessageId
- [x] MessageEntity
- [x] PhotoSize
- [x] Chat
- [x] Animation
- [x] Audio
- [x] Document
- [x] Video
- [x] VideoNote
- [x] Voice
- [x] Contact
- [x] Dice
- [x] Poll
- [x] PollOption
- [x] PollAnswer
- [x] Location
- [x] Venue
- [x] WebAppData
- [x] ProximityAlertTriggered
- [x] MessageAutoDeleteTimerChanged
- [x] VideoChatScheduled
- [x] VideoChatStarted
- [x] VideoChatEnded
- [x] VideoChatParticipantsInvited
- [x] UserProfilePhotos
- [x] File
- [x] WebAppInfo
- [x] ReplyKeyboardMarkup
- [x] KeyboardButton
- [x] KeyboardButtonPollType
- [x] ReplyKeyboardRemove
- [x] InlineKeyboardMarkup
- [x] InlineKeyboardButton
- [x] LoginUrl
- [x] CallbackQuery
- [x] ForceReply
- [x] ChatPhoto
- [x] ChatInviteLink
- [x] ChatAdministratorRights
- [x] ChatMember
- [x] ChatMemberOwner
- [x] ChatMemberAdministrator
- [x] ChatMemberMember
- [x] ChatMemberRestricted
- [x] ChatMemberLeft
- [x] ChatMemberBanned
- [x] ChatMemberUpdated
- [x] ChatJoinRequest
- [x] ChatPermissions
- [x] ChatLocation
- [x] BotCommand
- [x] BotCommandScope
- [x] BotCommandScopeDefault
- [x] BotCommandScopeAllPrivateChats
- [x] BotCommandScopeAllGroupChats
- [x] BotCommandScopeAllChatAdministrattos
- [x] BotCommandScopeChat
- [x] BotCommandScopeChat
- [x] BotCommandScopeChatAdministrators
- [x] BotCommandScopeChatMember
- [x] MenuButton
- [x] MenuButtonCommands
- [x] MenuButtonWebApp
- [x] MenuButtonDefault
- [x] ResponsePrarameters
- [x] InputMedia
- [x] InputMediaPhoto
- [x] InputMediaVideo
- [x] InputMediaAnimation
- [x] InputMediaAudio
- [x] InputMediaDocument
- [x] InputFile

**Comment by moses-kisakye** [comment]
Hi, am seeing some checked **objects** and yet they are not yet worked Upon!! I guess that needs to be worked on early enough to avoid confusion & repetition. Though am looking presenting.
Thank you

**Comment by ht-thomas** [comment]
@moses-kisakye which objects are those so that I can uncheck them

**Comment by moses-kisakye** [comment]
@ht-thomas 

### I think these are checked but not worked on!

- [ ] InputMedia
- [ ] InputMediaPhoto
- [ ] InputMediaVideo
- [ ] InputMediaAnimation
- [ ] InputMediaAudio
- [ ] InputMediaDocument
- [ ] BotCommandScope
- [ ] KeyboardButtonPollType
- [ ] UserProfilePhotos
- [ ] WebAppData
- [ ] VideoNote
- [ ] MessageEntity
- [ ] MessageId

### And these are done but not checked!

- [ ] Animation
- [ ] Base
- [ ] CallbackQuery
- [ ] ChatMember
- [ ] Contact
- [ ] Dice
- [ ] Document
- [ ] ForceReply
- [ ] Inlinekeyboard
- [ ] Location
- [ ] LoginUrl
- [ ] MenuButton
- [ ] PhotoSize
- [ ] Poll
- [ ] ProximityAlertTriggered
- [ ] ReplyKeyboard
- [ ] ResponseParameters
- [ ] Voice
- [ ] WebApp

**Comment by ht-thomas** [comment]
@moses-kisakye perhaps I need to first understand what you mean by being worked on.

**Comment by moses-kisakye** [comment]
@ht-thomas 
what am trying to mean is that they are  checked but yet not solved!!!
am i getting this right?

**Comment by ht-thomas** [comment]
@moses-kisakye the intention of the issue we're working on just fill in the properties into the empty classes as I had described earlier. Any pull request that did that was reviewed and merged. So that why I'm wondering what you're meant by not been solved

**Comment by moses-kisakye** [comment]
@ht-thomas 
Oooh Thank You For That Information!
