### ISSUE TITLE
add remaining telegram objects

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#38]
We've tried to cover the biggest and general purpose telegram objects. However, there are a few more special purposed objects we need to include to make the ground complete. More specifically, the **Inline mode** objects, **Passport** objects, **payment** objects, **games** objects and **stickers** objects. Since these objects are already related, the shall live in the objects module of their respective object types. I've created subpackages (folders) for each of these objects plus some empty module files.

**Note:** Please ignore the `api.py` and `__init__.py` files you encounter in these subpackages, they shall be worked on later. For now, we need to identify the respective object types as listed in the telegram bot documentation. Below is our task list.

### [stickers](https://core.telegram.org/bots/api#stickers)
- [x] Sticker
- [x] StickerSet
- [x] MaskPosition

### [Inline](https://core.telegram.org/bots/api#inline-mode)
- [x] InlineQuery
- [x] InlineQueryResultCachedAudio
- [x] InlineQueryResultCachedDocument
- [x] InlineQueryResultCachedGif
- [x] InlineQueryResultCachedMpeg4Gif
- [x] InlineQueryResultCachedPhoto
- [x] InlineQueryResultCachedSticker
- [x] InlineQueryResultCachedVideo
- [x] InlineQueryResultCachedVoice
- [x] InlineQueryResultArticle
- [x] InlineQueryResultAudio
- [x] InlineQueryResultContact
- [x] InlineQueryResultGame
- [x] InlineQueryResultDocument
- [x] InlineQueryResultGif
- [x] InlineQueryResultLocation
- [x] InlineQueryResultMpeg4Gif
- [x] InlineQueryResultPhoto
- [x] InlineQueryResultVenue
- [x] InlineQueryResultVideo
- [x] InlineQueryResultVoice

### [Payments](https://core.telegram.org/bots/api#payments)
- [x] LabeledPrice
- [x] Invoice
- [x] ShippingAddress
- [x] OrderInfo
- [x] ShippingOption
- [x] SuccessfulPayment
- [x] ShippingQuery
- [x] PreCheckoutQuery

### [Passport](https://core.telegram.org/bots/api#telegram-passport)
- [x] PassportData
- [x] PassportFile
- [x] EncryptedPassportElement
- [x] EncryptedCredentials
- [x] PassportElementErrorDataField
- [x] PassportElementErrorFrontSide
- [x] PassportElementErrorReverseSide
- [x] PassportElementErrorSelfie
- [x] PassportElementErrorFile
- [x] PassportElementErrorFiles
- [x] PassportElementErrorTranslationFile
- [x] PassportElementErrorTranslationFiles
- [x] PassportElementErrorUnspecified

### [Games](https://core.telegram.org/bots/api#games)
- [x] Game
- [x] GameHighScore

**Comment by kallyas** [comment]
Currently working on Inline

**Comment by edger-asiimwe** [comment]
@kallyas Kindly let me know which classes you've worked on the **inline** module

**Comment by kallyas** [comment]
InlineQueryResultCachedAudio
 InlineQueryResultCachedDocument
 InlineQueryResultCachedGif
 InlineQueryResultCachedMpeg4Gif
 InlineQueryResultCachedPhoto
 InlineQueryResultCachedSticker
 InlineQueryResultCachedVideo

**Comment by kallyas** [comment]
@ht-thomas @edger-asiimwe @ushergodwin I think we can close this issue since all the objects have been added, unless there are more that are not listed here yet

**Comment by ht-thomas** [comment]
@kallyas you should close this if you can.
