### ISSUE TITLE
Typing sprint

### ISSUE THREAD

**Issue by ht-thomas** [OSCA-Kampala-Chapter/autobot#50]
We need to add type annotations to make autobot 100% typed before the code base gets too big. 
Typing will ensure easy debugging of code and proper documentation.

### Typing summary
Python allows type annotations in basically two area, ie, variable declaration and function signatures.
variable annotations are done in the form:
`name:type = value` for example
`a:int = 0`
function signature annotations are done in the form:
`def name (annotated-parameters) -> return-type:`
for example:
```python
def add (a:int = 1,b:int = 1) -> int:
    return a+b
```
realpython has a number of articles to help you grasp typing quickly, and also the python documentation [here](https://docs.python.org/3.10/library/typing.html) has a python typing description in detail.

### what to do
Basically we shall focus more on function signature typing and ignore variable typing unless the variables are global variables of that module, or if they are declared in the initialization function of that class with a default value of None. For functions that take parameters of a specific telegram type, import that class and add it as a type hint to the parameter. 
For example.
```python
# this is an example of a hypothetical function 
# that takes a chat object and returns it's title as a string
from autobot.telegram.objects import Chat

def get_title (chat:Chat) -> str:
    return chat.title
```
this is an example for declaring an object whose variables in the initialize function rely on other object types
```python
from autobot.telegram.objects import Chat,Message,User
# abstract object that takes in random stuff in its __init__ function
# this is just for demonstration, it's not real.
class Abyss:
    def __init__ (self,cake:str) -> None:
        self.content:Chat = None
        self.words:Message = None
        self.person:User = None
```
so basically we are going to type every object that we have worked on so far, this time let us type by module, ie, someone should type every object in a given module and make a pull request referencing this issue so that we keep track of the modules that have been typed.
### commit format
The commit message should be in the form `gh-this_issue_number: typing module_name completed`.

You can find the type of the properties on the `type` column of the object on the telegram bot api page.
If you have any questions, feel free to ask a question on the discussion topic here #49

Let the Typing Sprint begin 🥳

**Comment by ht-thomas** [comment]
@ushergodwin @kallyas @edger-asiimwe is this issue completed so we can close it? it's as if it's complete

**Comment by kallyas** [comment]
As far I'm concerned, I think it's 100% complete unless otherwise
