### ISSUE TITLE
Missing InputMessageContent Object

### ISSUE THREAD

**Issue by kallyas** [OSCA-Kampala-Chapter/autobot#56]
I have noticed that the `InputMessageContent` object is missing from the codebase. 
This is causing problems for our users who are trying to use the `InputMessageContent` object. 
I would appreciate it if it could be added to the codebase so that our users can use it. 
Thank you.

**Comment by ht-thomas** [comment]
I cannot find the `InputMessageContent` object on the telegram bot api page. Where could it be needed?

**Comment by kallyas** [comment]
[InputMessageContent](https://core.telegram.org/bots/api#inputmessagecontent)

It is needed by most of  `InlineQueryResult*` Objects with `input_message_content` as the attribute (optional)

**Comment by ht-thomas** [comment]
@kallyas but it's as if it doesn't have any actual properties inside it, but rather an umbrella for the `Input*MessageContent* objects. One solution we can use is create it as a base class and have the rest of the objects subclass this. In this way, they type checker might still be able to detect the different subclasses as having a common type

**Comment by kallyas** [comment]
This should work for all MessageContents

**Comment by ushergodwin** [comment]
I had worked on this though I haven't pushed it.
