### ISSUE TITLE
Missing Object CallbackGame

### ISSUE THREAD

**Issue by kallyas** [OSCA-Kampala-Chapter/autobot#60]
Although `CallbackGame` is a placeholder that currently holds no information, it is an optional property to `InlineKeyboardMarkup` object thus not finding it for type hint to `callback_game` property of the `InlineKeyboardMarkup`

**Comment by ht-thomas** [comment]
@kallyas I think we should resolve these kinds of issues by creating a base class and have sublasses from it. Since I can't personally locate these objects, is it alright to assign you to this task?

**Comment by kallyas** [comment]
Thank you for bringing this up. I agree that creating a base class and having subclasses from it would be the best way to resolve these issues. I would be happy to take on this task.

**Comment by kallyas** [comment]
@ht-thomas Is it safe to create them in [base.py](https://github.com/OSCA-Kampala-Chapter/autobot/blob/main/autobot/telegram/objects/base.py) ?

**Comment by ht-thomas** [comment]
@kallyas I think it's best to create the base objects in the same files as the subclasses
